### ISSUE TITLE
Assistance with creating Pull request

### ISSUE THREAD

**Issue by Jasm72** [coinhall/yacar#2355]
Hello!

I was referred to create a pull request by the coinhall twitter account for adding a token/pool to the site. However I've never done that before so was looking to get some assistance in adding it. Here is some info on the token:

Name: CORGI
Chain: Neutron
Pool: Astroport
Astroport pair on Neutron Explorer (can also find Pool by searching CORGI in Astroport): https://neutron.celat.one/neutron-1/accounts/neutron1ps5gjwq8e4pxprw30q5xyka0sttf84z46xlg0vtt0walnyl49ckqsqdtha/overview

URL for token: https://www.babycorgi.wtf/

Tweet for reference: https://twitter.com/coinhall_org/status/1736631608411869635

Thank you in advance!

**Comment by yusufaine** [comment]
closed in 142a851
